// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GlobalSyncObject.proto

package com.EPartition;

public final class GlobalSyncObject {
  private GlobalSyncObject() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SyncObjectOrBuilder extends
      // @@protoc_insertion_point(interface_extends:EPartiton.SyncObject)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.EPartiton.SyncObject.ReplicationDegree repDeg = 1;</code>
     */
    boolean hasRepDeg();
    /**
     * <code>.EPartiton.SyncObject.ReplicationDegree repDeg = 1;</code>
     */
    com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree getRepDeg();
    /**
     * <code>.EPartiton.SyncObject.ReplicationDegree repDeg = 1;</code>
     */
    com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegreeOrBuilder getRepDegOrBuilder();

    /**
     * <code>repeated .EPartiton.SyncObject.LoadStatusObject lso = 2;</code>
     */
    java.util.List<com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject> 
        getLsoList();
    /**
     * <code>repeated .EPartiton.SyncObject.LoadStatusObject lso = 2;</code>
     */
    com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject getLso(int index);
    /**
     * <code>repeated .EPartiton.SyncObject.LoadStatusObject lso = 2;</code>
     */
    int getLsoCount();
    /**
     * <code>repeated .EPartiton.SyncObject.LoadStatusObject lso = 2;</code>
     */
    java.util.List<? extends com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObjectOrBuilder> 
        getLsoOrBuilderList();
    /**
     * <code>repeated .EPartiton.SyncObject.LoadStatusObject lso = 2;</code>
     */
    com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObjectOrBuilder getLsoOrBuilder(
        int index);

    /**
     * <code>int32 curSync = 3;</code>
     */
    int getCurSync();
  }
  /**
   * Protobuf type {@code EPartiton.SyncObject}
   */
  public  static final class SyncObject extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:EPartiton.SyncObject)
      SyncObjectOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SyncObject.newBuilder() to construct.
    private SyncObject(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SyncObject() {
      lso_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SyncObject(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree.Builder subBuilder = null;
              if (repDeg_ != null) {
                subBuilder = repDeg_.toBuilder();
              }
              repDeg_ = input.readMessage(com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(repDeg_);
                repDeg_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                lso_ = new java.util.ArrayList<com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject>();
                mutable_bitField0_ |= 0x00000002;
              }
              lso_.add(
                  input.readMessage(com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject.parser(), extensionRegistry));
              break;
            }
            case 24: {

              curSync_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          lso_ = java.util.Collections.unmodifiableList(lso_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.EPartition.GlobalSyncObject.internal_static_EPartiton_SyncObject_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.EPartition.GlobalSyncObject.internal_static_EPartiton_SyncObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.EPartition.GlobalSyncObject.SyncObject.class, com.EPartition.GlobalSyncObject.SyncObject.Builder.class);
    }

    public interface ReplicationDegreeOrBuilder extends
        // @@protoc_insertion_point(interface_extends:EPartiton.SyncObject.ReplicationDegree)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>double repDegDouble = 1;</code>
       */
      double getRepDegDouble();

      /**
       * <code>int32 repDegInt = 2;</code>
       */
      int getRepDegInt();
    }
    /**
     * Protobuf type {@code EPartiton.SyncObject.ReplicationDegree}
     */
    public  static final class ReplicationDegree extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:EPartiton.SyncObject.ReplicationDegree)
        ReplicationDegreeOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use ReplicationDegree.newBuilder() to construct.
      private ReplicationDegree(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private ReplicationDegree() {
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private ReplicationDegree(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 9: {

                repDegDouble_ = input.readDouble();
                break;
              }
              case 16: {

                repDegInt_ = input.readInt32();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.EPartition.GlobalSyncObject.internal_static_EPartiton_SyncObject_ReplicationDegree_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.EPartition.GlobalSyncObject.internal_static_EPartiton_SyncObject_ReplicationDegree_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree.class, com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree.Builder.class);
      }

      public static final int REPDEGDOUBLE_FIELD_NUMBER = 1;
      private double repDegDouble_;
      /**
       * <code>double repDegDouble = 1;</code>
       */
      public double getRepDegDouble() {
        return repDegDouble_;
      }

      public static final int REPDEGINT_FIELD_NUMBER = 2;
      private int repDegInt_;
      /**
       * <code>int32 repDegInt = 2;</code>
       */
      public int getRepDegInt() {
        return repDegInt_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (repDegDouble_ != 0D) {
          output.writeDouble(1, repDegDouble_);
        }
        if (repDegInt_ != 0) {
          output.writeInt32(2, repDegInt_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (repDegDouble_ != 0D) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(1, repDegDouble_);
        }
        if (repDegInt_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, repDegInt_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree)) {
          return super.equals(obj);
        }
        com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree other = (com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree) obj;

        if (java.lang.Double.doubleToLongBits(getRepDegDouble())
            != java.lang.Double.doubleToLongBits(
                other.getRepDegDouble())) return false;
        if (getRepDegInt()
            != other.getRepDegInt()) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + REPDEGDOUBLE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getRepDegDouble()));
        hash = (37 * hash) + REPDEGINT_FIELD_NUMBER;
        hash = (53 * hash) + getRepDegInt();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code EPartiton.SyncObject.ReplicationDegree}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:EPartiton.SyncObject.ReplicationDegree)
          com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegreeOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.EPartition.GlobalSyncObject.internal_static_EPartiton_SyncObject_ReplicationDegree_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.EPartition.GlobalSyncObject.internal_static_EPartiton_SyncObject_ReplicationDegree_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree.class, com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree.Builder.class);
        }

        // Construct using com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          repDegDouble_ = 0D;

          repDegInt_ = 0;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.EPartition.GlobalSyncObject.internal_static_EPartiton_SyncObject_ReplicationDegree_descriptor;
        }

        @java.lang.Override
        public com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree getDefaultInstanceForType() {
          return com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree.getDefaultInstance();
        }

        @java.lang.Override
        public com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree build() {
          com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree buildPartial() {
          com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree result = new com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree(this);
          result.repDegDouble_ = repDegDouble_;
          result.repDegInt_ = repDegInt_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree) {
            return mergeFrom((com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree other) {
          if (other == com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree.getDefaultInstance()) return this;
          if (other.getRepDegDouble() != 0D) {
            setRepDegDouble(other.getRepDegDouble());
          }
          if (other.getRepDegInt() != 0) {
            setRepDegInt(other.getRepDegInt());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private double repDegDouble_ ;
        /**
         * <code>double repDegDouble = 1;</code>
         */
        public double getRepDegDouble() {
          return repDegDouble_;
        }
        /**
         * <code>double repDegDouble = 1;</code>
         */
        public Builder setRepDegDouble(double value) {
          
          repDegDouble_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>double repDegDouble = 1;</code>
         */
        public Builder clearRepDegDouble() {
          
          repDegDouble_ = 0D;
          onChanged();
          return this;
        }

        private int repDegInt_ ;
        /**
         * <code>int32 repDegInt = 2;</code>
         */
        public int getRepDegInt() {
          return repDegInt_;
        }
        /**
         * <code>int32 repDegInt = 2;</code>
         */
        public Builder setRepDegInt(int value) {
          
          repDegInt_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 repDegInt = 2;</code>
         */
        public Builder clearRepDegInt() {
          
          repDegInt_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:EPartiton.SyncObject.ReplicationDegree)
      }

      // @@protoc_insertion_point(class_scope:EPartiton.SyncObject.ReplicationDegree)
      private static final com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree();
      }

      public static com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<ReplicationDegree>
          PARSER = new com.google.protobuf.AbstractParser<ReplicationDegree>() {
        @java.lang.Override
        public ReplicationDegree parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new ReplicationDegree(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<ReplicationDegree> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<ReplicationDegree> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public interface LoadStatusObjectOrBuilder extends
        // @@protoc_insertion_point(interface_extends:EPartiton.SyncObject.LoadStatusObject)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string BROKER_IP = 1;</code>
       */
      java.lang.String getBROKERIP();
      /**
       * <code>string BROKER_IP = 1;</code>
       */
      com.google.protobuf.ByteString
          getBROKERIPBytes();

      /**
       * <code>int32 numSubscriptions = 2;</code>
       */
      int getNumSubscriptions();

      /**
       * <code>int32 accessCount = 3;</code>
       */
      int getAccessCount();
    }
    /**
     * Protobuf type {@code EPartiton.SyncObject.LoadStatusObject}
     */
    public  static final class LoadStatusObject extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:EPartiton.SyncObject.LoadStatusObject)
        LoadStatusObjectOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use LoadStatusObject.newBuilder() to construct.
      private LoadStatusObject(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private LoadStatusObject() {
        bROKERIP_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private LoadStatusObject(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                bROKERIP_ = s;
                break;
              }
              case 16: {

                numSubscriptions_ = input.readInt32();
                break;
              }
              case 24: {

                accessCount_ = input.readInt32();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.EPartition.GlobalSyncObject.internal_static_EPartiton_SyncObject_LoadStatusObject_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.EPartition.GlobalSyncObject.internal_static_EPartiton_SyncObject_LoadStatusObject_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject.class, com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject.Builder.class);
      }

      public static final int BROKER_IP_FIELD_NUMBER = 1;
      private volatile java.lang.Object bROKERIP_;
      /**
       * <code>string BROKER_IP = 1;</code>
       */
      public java.lang.String getBROKERIP() {
        java.lang.Object ref = bROKERIP_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bROKERIP_ = s;
          return s;
        }
      }
      /**
       * <code>string BROKER_IP = 1;</code>
       */
      public com.google.protobuf.ByteString
          getBROKERIPBytes() {
        java.lang.Object ref = bROKERIP_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bROKERIP_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int NUMSUBSCRIPTIONS_FIELD_NUMBER = 2;
      private int numSubscriptions_;
      /**
       * <code>int32 numSubscriptions = 2;</code>
       */
      public int getNumSubscriptions() {
        return numSubscriptions_;
      }

      public static final int ACCESSCOUNT_FIELD_NUMBER = 3;
      private int accessCount_;
      /**
       * <code>int32 accessCount = 3;</code>
       */
      public int getAccessCount() {
        return accessCount_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getBROKERIPBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, bROKERIP_);
        }
        if (numSubscriptions_ != 0) {
          output.writeInt32(2, numSubscriptions_);
        }
        if (accessCount_ != 0) {
          output.writeInt32(3, accessCount_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getBROKERIPBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, bROKERIP_);
        }
        if (numSubscriptions_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, numSubscriptions_);
        }
        if (accessCount_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, accessCount_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject)) {
          return super.equals(obj);
        }
        com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject other = (com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject) obj;

        if (!getBROKERIP()
            .equals(other.getBROKERIP())) return false;
        if (getNumSubscriptions()
            != other.getNumSubscriptions()) return false;
        if (getAccessCount()
            != other.getAccessCount()) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + BROKER_IP_FIELD_NUMBER;
        hash = (53 * hash) + getBROKERIP().hashCode();
        hash = (37 * hash) + NUMSUBSCRIPTIONS_FIELD_NUMBER;
        hash = (53 * hash) + getNumSubscriptions();
        hash = (37 * hash) + ACCESSCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getAccessCount();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code EPartiton.SyncObject.LoadStatusObject}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:EPartiton.SyncObject.LoadStatusObject)
          com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObjectOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.EPartition.GlobalSyncObject.internal_static_EPartiton_SyncObject_LoadStatusObject_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.EPartition.GlobalSyncObject.internal_static_EPartiton_SyncObject_LoadStatusObject_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject.class, com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject.Builder.class);
        }

        // Construct using com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bROKERIP_ = "";

          numSubscriptions_ = 0;

          accessCount_ = 0;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.EPartition.GlobalSyncObject.internal_static_EPartiton_SyncObject_LoadStatusObject_descriptor;
        }

        @java.lang.Override
        public com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject getDefaultInstanceForType() {
          return com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject.getDefaultInstance();
        }

        @java.lang.Override
        public com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject build() {
          com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject buildPartial() {
          com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject result = new com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject(this);
          result.bROKERIP_ = bROKERIP_;
          result.numSubscriptions_ = numSubscriptions_;
          result.accessCount_ = accessCount_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject) {
            return mergeFrom((com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject other) {
          if (other == com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject.getDefaultInstance()) return this;
          if (!other.getBROKERIP().isEmpty()) {
            bROKERIP_ = other.bROKERIP_;
            onChanged();
          }
          if (other.getNumSubscriptions() != 0) {
            setNumSubscriptions(other.getNumSubscriptions());
          }
          if (other.getAccessCount() != 0) {
            setAccessCount(other.getAccessCount());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object bROKERIP_ = "";
        /**
         * <code>string BROKER_IP = 1;</code>
         */
        public java.lang.String getBROKERIP() {
          java.lang.Object ref = bROKERIP_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            bROKERIP_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string BROKER_IP = 1;</code>
         */
        public com.google.protobuf.ByteString
            getBROKERIPBytes() {
          java.lang.Object ref = bROKERIP_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            bROKERIP_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string BROKER_IP = 1;</code>
         */
        public Builder setBROKERIP(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          bROKERIP_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string BROKER_IP = 1;</code>
         */
        public Builder clearBROKERIP() {
          
          bROKERIP_ = getDefaultInstance().getBROKERIP();
          onChanged();
          return this;
        }
        /**
         * <code>string BROKER_IP = 1;</code>
         */
        public Builder setBROKERIPBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          bROKERIP_ = value;
          onChanged();
          return this;
        }

        private int numSubscriptions_ ;
        /**
         * <code>int32 numSubscriptions = 2;</code>
         */
        public int getNumSubscriptions() {
          return numSubscriptions_;
        }
        /**
         * <code>int32 numSubscriptions = 2;</code>
         */
        public Builder setNumSubscriptions(int value) {
          
          numSubscriptions_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 numSubscriptions = 2;</code>
         */
        public Builder clearNumSubscriptions() {
          
          numSubscriptions_ = 0;
          onChanged();
          return this;
        }

        private int accessCount_ ;
        /**
         * <code>int32 accessCount = 3;</code>
         */
        public int getAccessCount() {
          return accessCount_;
        }
        /**
         * <code>int32 accessCount = 3;</code>
         */
        public Builder setAccessCount(int value) {
          
          accessCount_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 accessCount = 3;</code>
         */
        public Builder clearAccessCount() {
          
          accessCount_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:EPartiton.SyncObject.LoadStatusObject)
      }

      // @@protoc_insertion_point(class_scope:EPartiton.SyncObject.LoadStatusObject)
      private static final com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject();
      }

      public static com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<LoadStatusObject>
          PARSER = new com.google.protobuf.AbstractParser<LoadStatusObject>() {
        @java.lang.Override
        public LoadStatusObject parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new LoadStatusObject(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<LoadStatusObject> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<LoadStatusObject> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int REPDEG_FIELD_NUMBER = 1;
    private com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree repDeg_;
    /**
     * <code>.EPartiton.SyncObject.ReplicationDegree repDeg = 1;</code>
     */
    public boolean hasRepDeg() {
      return repDeg_ != null;
    }
    /**
     * <code>.EPartiton.SyncObject.ReplicationDegree repDeg = 1;</code>
     */
    public com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree getRepDeg() {
      return repDeg_ == null ? com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree.getDefaultInstance() : repDeg_;
    }
    /**
     * <code>.EPartiton.SyncObject.ReplicationDegree repDeg = 1;</code>
     */
    public com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegreeOrBuilder getRepDegOrBuilder() {
      return getRepDeg();
    }

    public static final int LSO_FIELD_NUMBER = 2;
    private java.util.List<com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject> lso_;
    /**
     * <code>repeated .EPartiton.SyncObject.LoadStatusObject lso = 2;</code>
     */
    public java.util.List<com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject> getLsoList() {
      return lso_;
    }
    /**
     * <code>repeated .EPartiton.SyncObject.LoadStatusObject lso = 2;</code>
     */
    public java.util.List<? extends com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObjectOrBuilder> 
        getLsoOrBuilderList() {
      return lso_;
    }
    /**
     * <code>repeated .EPartiton.SyncObject.LoadStatusObject lso = 2;</code>
     */
    public int getLsoCount() {
      return lso_.size();
    }
    /**
     * <code>repeated .EPartiton.SyncObject.LoadStatusObject lso = 2;</code>
     */
    public com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject getLso(int index) {
      return lso_.get(index);
    }
    /**
     * <code>repeated .EPartiton.SyncObject.LoadStatusObject lso = 2;</code>
     */
    public com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObjectOrBuilder getLsoOrBuilder(
        int index) {
      return lso_.get(index);
    }

    public static final int CURSYNC_FIELD_NUMBER = 3;
    private int curSync_;
    /**
     * <code>int32 curSync = 3;</code>
     */
    public int getCurSync() {
      return curSync_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (repDeg_ != null) {
        output.writeMessage(1, getRepDeg());
      }
      for (int i = 0; i < lso_.size(); i++) {
        output.writeMessage(2, lso_.get(i));
      }
      if (curSync_ != 0) {
        output.writeInt32(3, curSync_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (repDeg_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRepDeg());
      }
      for (int i = 0; i < lso_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, lso_.get(i));
      }
      if (curSync_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, curSync_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.EPartition.GlobalSyncObject.SyncObject)) {
        return super.equals(obj);
      }
      com.EPartition.GlobalSyncObject.SyncObject other = (com.EPartition.GlobalSyncObject.SyncObject) obj;

      if (hasRepDeg() != other.hasRepDeg()) return false;
      if (hasRepDeg()) {
        if (!getRepDeg()
            .equals(other.getRepDeg())) return false;
      }
      if (!getLsoList()
          .equals(other.getLsoList())) return false;
      if (getCurSync()
          != other.getCurSync()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRepDeg()) {
        hash = (37 * hash) + REPDEG_FIELD_NUMBER;
        hash = (53 * hash) + getRepDeg().hashCode();
      }
      if (getLsoCount() > 0) {
        hash = (37 * hash) + LSO_FIELD_NUMBER;
        hash = (53 * hash) + getLsoList().hashCode();
      }
      hash = (37 * hash) + CURSYNC_FIELD_NUMBER;
      hash = (53 * hash) + getCurSync();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.EPartition.GlobalSyncObject.SyncObject parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.EPartition.GlobalSyncObject.SyncObject parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.EPartition.GlobalSyncObject.SyncObject parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.EPartition.GlobalSyncObject.SyncObject parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.EPartition.GlobalSyncObject.SyncObject parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.EPartition.GlobalSyncObject.SyncObject parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.EPartition.GlobalSyncObject.SyncObject parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.EPartition.GlobalSyncObject.SyncObject parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.EPartition.GlobalSyncObject.SyncObject parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.EPartition.GlobalSyncObject.SyncObject parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.EPartition.GlobalSyncObject.SyncObject parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.EPartition.GlobalSyncObject.SyncObject parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.EPartition.GlobalSyncObject.SyncObject prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code EPartiton.SyncObject}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:EPartiton.SyncObject)
        com.EPartition.GlobalSyncObject.SyncObjectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.EPartition.GlobalSyncObject.internal_static_EPartiton_SyncObject_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.EPartition.GlobalSyncObject.internal_static_EPartiton_SyncObject_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.EPartition.GlobalSyncObject.SyncObject.class, com.EPartition.GlobalSyncObject.SyncObject.Builder.class);
      }

      // Construct using com.EPartition.GlobalSyncObject.SyncObject.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getLsoFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (repDegBuilder_ == null) {
          repDeg_ = null;
        } else {
          repDeg_ = null;
          repDegBuilder_ = null;
        }
        if (lsoBuilder_ == null) {
          lso_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          lsoBuilder_.clear();
        }
        curSync_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.EPartition.GlobalSyncObject.internal_static_EPartiton_SyncObject_descriptor;
      }

      @java.lang.Override
      public com.EPartition.GlobalSyncObject.SyncObject getDefaultInstanceForType() {
        return com.EPartition.GlobalSyncObject.SyncObject.getDefaultInstance();
      }

      @java.lang.Override
      public com.EPartition.GlobalSyncObject.SyncObject build() {
        com.EPartition.GlobalSyncObject.SyncObject result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.EPartition.GlobalSyncObject.SyncObject buildPartial() {
        com.EPartition.GlobalSyncObject.SyncObject result = new com.EPartition.GlobalSyncObject.SyncObject(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (repDegBuilder_ == null) {
          result.repDeg_ = repDeg_;
        } else {
          result.repDeg_ = repDegBuilder_.build();
        }
        if (lsoBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            lso_ = java.util.Collections.unmodifiableList(lso_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.lso_ = lso_;
        } else {
          result.lso_ = lsoBuilder_.build();
        }
        result.curSync_ = curSync_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.EPartition.GlobalSyncObject.SyncObject) {
          return mergeFrom((com.EPartition.GlobalSyncObject.SyncObject)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.EPartition.GlobalSyncObject.SyncObject other) {
        if (other == com.EPartition.GlobalSyncObject.SyncObject.getDefaultInstance()) return this;
        if (other.hasRepDeg()) {
          mergeRepDeg(other.getRepDeg());
        }
        if (lsoBuilder_ == null) {
          if (!other.lso_.isEmpty()) {
            if (lso_.isEmpty()) {
              lso_ = other.lso_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureLsoIsMutable();
              lso_.addAll(other.lso_);
            }
            onChanged();
          }
        } else {
          if (!other.lso_.isEmpty()) {
            if (lsoBuilder_.isEmpty()) {
              lsoBuilder_.dispose();
              lsoBuilder_ = null;
              lso_ = other.lso_;
              bitField0_ = (bitField0_ & ~0x00000002);
              lsoBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getLsoFieldBuilder() : null;
            } else {
              lsoBuilder_.addAllMessages(other.lso_);
            }
          }
        }
        if (other.getCurSync() != 0) {
          setCurSync(other.getCurSync());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.EPartition.GlobalSyncObject.SyncObject parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.EPartition.GlobalSyncObject.SyncObject) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree repDeg_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree, com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree.Builder, com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegreeOrBuilder> repDegBuilder_;
      /**
       * <code>.EPartiton.SyncObject.ReplicationDegree repDeg = 1;</code>
       */
      public boolean hasRepDeg() {
        return repDegBuilder_ != null || repDeg_ != null;
      }
      /**
       * <code>.EPartiton.SyncObject.ReplicationDegree repDeg = 1;</code>
       */
      public com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree getRepDeg() {
        if (repDegBuilder_ == null) {
          return repDeg_ == null ? com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree.getDefaultInstance() : repDeg_;
        } else {
          return repDegBuilder_.getMessage();
        }
      }
      /**
       * <code>.EPartiton.SyncObject.ReplicationDegree repDeg = 1;</code>
       */
      public Builder setRepDeg(com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree value) {
        if (repDegBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          repDeg_ = value;
          onChanged();
        } else {
          repDegBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.EPartiton.SyncObject.ReplicationDegree repDeg = 1;</code>
       */
      public Builder setRepDeg(
          com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree.Builder builderForValue) {
        if (repDegBuilder_ == null) {
          repDeg_ = builderForValue.build();
          onChanged();
        } else {
          repDegBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.EPartiton.SyncObject.ReplicationDegree repDeg = 1;</code>
       */
      public Builder mergeRepDeg(com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree value) {
        if (repDegBuilder_ == null) {
          if (repDeg_ != null) {
            repDeg_ =
              com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree.newBuilder(repDeg_).mergeFrom(value).buildPartial();
          } else {
            repDeg_ = value;
          }
          onChanged();
        } else {
          repDegBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.EPartiton.SyncObject.ReplicationDegree repDeg = 1;</code>
       */
      public Builder clearRepDeg() {
        if (repDegBuilder_ == null) {
          repDeg_ = null;
          onChanged();
        } else {
          repDeg_ = null;
          repDegBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.EPartiton.SyncObject.ReplicationDegree repDeg = 1;</code>
       */
      public com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree.Builder getRepDegBuilder() {
        
        onChanged();
        return getRepDegFieldBuilder().getBuilder();
      }
      /**
       * <code>.EPartiton.SyncObject.ReplicationDegree repDeg = 1;</code>
       */
      public com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegreeOrBuilder getRepDegOrBuilder() {
        if (repDegBuilder_ != null) {
          return repDegBuilder_.getMessageOrBuilder();
        } else {
          return repDeg_ == null ?
              com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree.getDefaultInstance() : repDeg_;
        }
      }
      /**
       * <code>.EPartiton.SyncObject.ReplicationDegree repDeg = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree, com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree.Builder, com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegreeOrBuilder> 
          getRepDegFieldBuilder() {
        if (repDegBuilder_ == null) {
          repDegBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree, com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegree.Builder, com.EPartition.GlobalSyncObject.SyncObject.ReplicationDegreeOrBuilder>(
                  getRepDeg(),
                  getParentForChildren(),
                  isClean());
          repDeg_ = null;
        }
        return repDegBuilder_;
      }

      private java.util.List<com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject> lso_ =
        java.util.Collections.emptyList();
      private void ensureLsoIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          lso_ = new java.util.ArrayList<com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject>(lso_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject, com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject.Builder, com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObjectOrBuilder> lsoBuilder_;

      /**
       * <code>repeated .EPartiton.SyncObject.LoadStatusObject lso = 2;</code>
       */
      public java.util.List<com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject> getLsoList() {
        if (lsoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(lso_);
        } else {
          return lsoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .EPartiton.SyncObject.LoadStatusObject lso = 2;</code>
       */
      public int getLsoCount() {
        if (lsoBuilder_ == null) {
          return lso_.size();
        } else {
          return lsoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .EPartiton.SyncObject.LoadStatusObject lso = 2;</code>
       */
      public com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject getLso(int index) {
        if (lsoBuilder_ == null) {
          return lso_.get(index);
        } else {
          return lsoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .EPartiton.SyncObject.LoadStatusObject lso = 2;</code>
       */
      public Builder setLso(
          int index, com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject value) {
        if (lsoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLsoIsMutable();
          lso_.set(index, value);
          onChanged();
        } else {
          lsoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .EPartiton.SyncObject.LoadStatusObject lso = 2;</code>
       */
      public Builder setLso(
          int index, com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject.Builder builderForValue) {
        if (lsoBuilder_ == null) {
          ensureLsoIsMutable();
          lso_.set(index, builderForValue.build());
          onChanged();
        } else {
          lsoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .EPartiton.SyncObject.LoadStatusObject lso = 2;</code>
       */
      public Builder addLso(com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject value) {
        if (lsoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLsoIsMutable();
          lso_.add(value);
          onChanged();
        } else {
          lsoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .EPartiton.SyncObject.LoadStatusObject lso = 2;</code>
       */
      public Builder addLso(
          int index, com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject value) {
        if (lsoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLsoIsMutable();
          lso_.add(index, value);
          onChanged();
        } else {
          lsoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .EPartiton.SyncObject.LoadStatusObject lso = 2;</code>
       */
      public Builder addLso(
          com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject.Builder builderForValue) {
        if (lsoBuilder_ == null) {
          ensureLsoIsMutable();
          lso_.add(builderForValue.build());
          onChanged();
        } else {
          lsoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .EPartiton.SyncObject.LoadStatusObject lso = 2;</code>
       */
      public Builder addLso(
          int index, com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject.Builder builderForValue) {
        if (lsoBuilder_ == null) {
          ensureLsoIsMutable();
          lso_.add(index, builderForValue.build());
          onChanged();
        } else {
          lsoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .EPartiton.SyncObject.LoadStatusObject lso = 2;</code>
       */
      public Builder addAllLso(
          java.lang.Iterable<? extends com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject> values) {
        if (lsoBuilder_ == null) {
          ensureLsoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, lso_);
          onChanged();
        } else {
          lsoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .EPartiton.SyncObject.LoadStatusObject lso = 2;</code>
       */
      public Builder clearLso() {
        if (lsoBuilder_ == null) {
          lso_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          lsoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .EPartiton.SyncObject.LoadStatusObject lso = 2;</code>
       */
      public Builder removeLso(int index) {
        if (lsoBuilder_ == null) {
          ensureLsoIsMutable();
          lso_.remove(index);
          onChanged();
        } else {
          lsoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .EPartiton.SyncObject.LoadStatusObject lso = 2;</code>
       */
      public com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject.Builder getLsoBuilder(
          int index) {
        return getLsoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .EPartiton.SyncObject.LoadStatusObject lso = 2;</code>
       */
      public com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObjectOrBuilder getLsoOrBuilder(
          int index) {
        if (lsoBuilder_ == null) {
          return lso_.get(index);  } else {
          return lsoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .EPartiton.SyncObject.LoadStatusObject lso = 2;</code>
       */
      public java.util.List<? extends com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObjectOrBuilder> 
           getLsoOrBuilderList() {
        if (lsoBuilder_ != null) {
          return lsoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(lso_);
        }
      }
      /**
       * <code>repeated .EPartiton.SyncObject.LoadStatusObject lso = 2;</code>
       */
      public com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject.Builder addLsoBuilder() {
        return getLsoFieldBuilder().addBuilder(
            com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject.getDefaultInstance());
      }
      /**
       * <code>repeated .EPartiton.SyncObject.LoadStatusObject lso = 2;</code>
       */
      public com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject.Builder addLsoBuilder(
          int index) {
        return getLsoFieldBuilder().addBuilder(
            index, com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject.getDefaultInstance());
      }
      /**
       * <code>repeated .EPartiton.SyncObject.LoadStatusObject lso = 2;</code>
       */
      public java.util.List<com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject.Builder> 
           getLsoBuilderList() {
        return getLsoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject, com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject.Builder, com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObjectOrBuilder> 
          getLsoFieldBuilder() {
        if (lsoBuilder_ == null) {
          lsoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject, com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObject.Builder, com.EPartition.GlobalSyncObject.SyncObject.LoadStatusObjectOrBuilder>(
                  lso_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          lso_ = null;
        }
        return lsoBuilder_;
      }

      private int curSync_ ;
      /**
       * <code>int32 curSync = 3;</code>
       */
      public int getCurSync() {
        return curSync_;
      }
      /**
       * <code>int32 curSync = 3;</code>
       */
      public Builder setCurSync(int value) {
        
        curSync_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 curSync = 3;</code>
       */
      public Builder clearCurSync() {
        
        curSync_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:EPartiton.SyncObject)
    }

    // @@protoc_insertion_point(class_scope:EPartiton.SyncObject)
    private static final com.EPartition.GlobalSyncObject.SyncObject DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.EPartition.GlobalSyncObject.SyncObject();
    }

    public static com.EPartition.GlobalSyncObject.SyncObject getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SyncObject>
        PARSER = new com.google.protobuf.AbstractParser<SyncObject>() {
      @java.lang.Override
      public SyncObject parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SyncObject(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SyncObject> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SyncObject> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.EPartition.GlobalSyncObject.SyncObject getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EPartiton_SyncObject_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EPartiton_SyncObject_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EPartiton_SyncObject_ReplicationDegree_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EPartiton_SyncObject_ReplicationDegree_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EPartiton_SyncObject_LoadStatusObject_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EPartiton_SyncObject_LoadStatusObject_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026GlobalSyncObject.proto\022\tEPartiton\"\237\002\n\n" +
      "SyncObject\0227\n\006repDeg\030\001 \001(\0132\'.EPartiton.S" +
      "yncObject.ReplicationDegree\0223\n\003lso\030\002 \003(\013" +
      "2&.EPartiton.SyncObject.LoadStatusObject" +
      "\022\017\n\007curSync\030\003 \001(\005\032<\n\021ReplicationDegree\022\024" +
      "\n\014repDegDouble\030\001 \001(\001\022\021\n\trepDegInt\030\002 \001(\005\032" +
      "T\n\020LoadStatusObject\022\021\n\tBROKER_IP\030\001 \001(\t\022\030" +
      "\n\020numSubscriptions\030\002 \001(\005\022\023\n\013accessCount\030" +
      "\003 \001(\005B\"\n\016com.EPartitionB\020GlobalSyncObjec" +
      "tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_EPartiton_SyncObject_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EPartiton_SyncObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EPartiton_SyncObject_descriptor,
        new java.lang.String[] { "RepDeg", "Lso", "CurSync", });
    internal_static_EPartiton_SyncObject_ReplicationDegree_descriptor =
      internal_static_EPartiton_SyncObject_descriptor.getNestedTypes().get(0);
    internal_static_EPartiton_SyncObject_ReplicationDegree_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EPartiton_SyncObject_ReplicationDegree_descriptor,
        new java.lang.String[] { "RepDegDouble", "RepDegInt", });
    internal_static_EPartiton_SyncObject_LoadStatusObject_descriptor =
      internal_static_EPartiton_SyncObject_descriptor.getNestedTypes().get(1);
    internal_static_EPartiton_SyncObject_LoadStatusObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EPartiton_SyncObject_LoadStatusObject_descriptor,
        new java.lang.String[] { "BROKERIP", "NumSubscriptions", "AccessCount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
